[FanControl]
# GPIO для управления транзистором (PWM)
pwm_gpio = 14

# GPIO для тахометра (обратная связь по оборотам)
tacho_gpio = 18

# Время между проверками (секунды)
wait_time = 2

# Частота ШИМ для управления вентилятором (Гц)
pwm_freq = 25

# Температурные пороги
min_temp = 50
min_cool_temp = 45
max_temp = 75

# Минимальный и максимальный duty cycle (0-100)
fan_low = 30
fan_high = 100

# Минимальные обороты для определения работы вентилятора (об/мин)
min_rpm = 500
